workflows:
  android-apk:
    name: Android Capacitor APK
    max_build_duration: 120
    instance_type: linux
    environment:
      node: latest
      android: true
    scripts:
      - name: Install deps
        script: npm ci
      - name: Build web
        script: npm run build
      - name: Capacitor sync Android
        script: npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-ipa:
    name: iOS Capacitor IPA
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Install deps
        script: npm ci
      - name: Build web
        script: npm run build
      - name: Capacitor sync iOS
        script: npx cap sync ios
      - name: Cocoapods install
        script: cd ios/App && pod install
      - name: Build IPA
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -derivedDataPath ../build -archivePath ../build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath ../build/App.xcarchive -exportPath ../build -exportOptionsPlist ExportOptions.plist
    artifacts:
      - ios/build/**/*.ipa
