workflows:
  android-apk-unsigned:
    name: Android APK (unsigned, for direct share)
    instance_type: mac_mini_m2      # gratuit
    max_build_duration: 20
    environment:
      node: 18.18
    scripts:
      - name: Install & build web
        script: |
          npm ci
          npm run build
          npx next export
      - name: Add Capacitor Android
        script: |
          npm install @capacitor/core @capacitor/android
          npx cap init PharmaApp com.pharmapp.app --web-dir out
          npx cap add android
          npx cap sync android
      - name: Build unsigned APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
