workflows:
  android-apk:
    name: Android Capacitor APK
    max_build_duration: 120
    instance_type: linux
    environment:
      node: latest
    scripts:
      - npm ci
      - npm run build
      - npx cap sync android
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-ipa:
    name: iOS Capacitor IPA
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: 15.4
      cocoapods: default
    scripts:
      - npm ci
      - npm run build
      - npx cap sync ios
      - cd ios/App && pod install
      - cd ios/App
      - xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -derivedDataPath ../build -archivePath ../build/App.xcarchive archive
      - xcodebuild -exportArchive -archivePath ../build/App.xcarchive -exportPath ../build -exportOptionsPlist ExportOptions.plist
    artifacts:
      - ios/build/**/*.ipa
